version: "3"
services:
  nginx:
    image: nginx:1.27.0
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./www/html/:/var/www/html/
      - ./www/logs/:/var/log/nginx/
      - ./www/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./www/html/:/var/www/html/
  mariadb:
    image: mariadb:11.4.2
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    networks:
      - internal
    volumes:
      - ./data/mysql/:/var/lib/mysql/
networks:
  internal:
    driver: bridge