services:
  nginx:
    image: nginx:1.26.2
    environment:
      TZ: America/Mazatlan
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./nginx/docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - ../www/html/:/var/www/html/
      - ../www/logs/:/var/log/nginx/
  php:
    build:
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./php/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
      - ../www/html/:/var/www/html/
  mariadb:
    image: mariadb:11.5.2
    environment:
      TZ: America/Mazatlan
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    networks:
      - internal
    volumes:
      - ./mariadb/data/mysql/:/var/lib/mysql/
      - ./mariadb/docker-mariadb.conf:/etc/mysql/conf.d/docker-mariadb.conf
networks:
  internal:
    driver: bridge