services:
  nginx:
    image: nginx:1.28.0
    environment:
      TZ: UTC
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/99-docker-nginx.conf:/etc/nginx/conf.d/99-docker-nginx.conf
      - ../www/html/:/var/www/html/
      - ../www/logs/:/var/log/nginx/
  php:
    build:
      dockerfile: php/Dockerfile
    environment:
      TZ: UTC
    networks:
      - internal
    volumes:
      - ./php/99-docker-php.ini:/usr/local/etc/php/conf.d/99-docker-php.ini
      - ../www/html/:/var/www/html/
  mariadb:
    image: mariadb:11.8.2
    environment:
      TZ: UTC
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    networks:
      - internal
    volumes:
      - ./mariadb/data/mysql/:/var/lib/mysql/
      - ./mariadb/99-docker-mariadb.conf:/etc/mysql/conf.d/99-docker-mariadb.conf
networks:
  internal:
    driver: bridge